language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm
before_script:
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: make travis
matrix:
    fast_finish: true
    allow_failures:
        - php: 5.3
        - php: 5.4
        - php: hhvm
        - php: nightly
